// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drzovfwilsmpkxfveoib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyem92ZndpbHNtcGt4ZnZlb2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjMyNzMsImV4cCI6MjA3MzkzOTI3M30.iE0Vs4H2RFEWABFoRig2elGN_Rqv4et13NIacMDDeSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});